modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "zombie_tactics"
version = "1.3.0"
displayName = "ZombieTactics"
authors = "n643064"
description = "Improves zombie mechanism"
logoFile = "assets/zombie_tactics/img.png"

[[dependencies.zombie_tactics]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombie_tactics]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombie_tactics]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "zombie_tactics.neoforge-mixins.json"

[[mixins]]
config = "zombie_tactics.mixins.json"
