modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "zombietactics2"
version = "$version"
displayName = "Zombie Tactics 2"
authors = "picopress"
description = "Improves zombie mechanism"
logoFile = "assets/zombietactics2/img.png"

[[dependencies.zombietactics2]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombietactics2]]
modId = "minecraft"
type = "required"
versionRange = "1.21.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombietactics2]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "zombietactics2.neoforge-mixins.json"

[[mixins]]
config = "zombietactics2.mixins.json"
