modLoader = "javafml"
loaderVersion = "[7,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "zombie_tactics"
version = "$version"
displayName = "ZombieTactics"
authors = "n643064"
description = "Improves zombie mechanism"
logoFile = "assets/zombie_tactics/img.png"

[[dependencies.zombie_tactics]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombie_tactics]]
modId = "minecraft"
type = "required"
versionRange = "1.21.5"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombie_tactics]]
modId = "architectury"
type = "required"
versionRange = "[16.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "zombie_tactics.neoforge-mixins.json"

[[mixins]]
config = "zombie_tactics.mixins.json"
